### ISSUE TITLE
Issue with executing python gprpyGUI.py command

### ISSUE THREAD

**Issue by learninguser** [NSGeophysics/GPRPy#1]
Hello,
I am trying to install GPRPy on my system. I am using Ubuntu 18.04 and miniconda with Python 3.6.6 version on it. Please take a look at the error mentioned below and let me know how to resolve it.
`Traceback (most recent call last):
  File "gprpyGUI.py", line 13, in <module>
    import matplotlib as mpl
  File "/home/pavan/miniconda3/envs/gprMax/lib/python3.6/site-packages/matplotlib/__init__.py", line 210, in <module>
    if not compare_versions(numpy.__version__, __version__numpy__):
AttributeError: module 'numpy' has no attribute '__version__'
`
Thanks in advance.
Pavan.

**Comment by AlainPlattner** [comment]
Hi,

Thanks for using GPRPy.

From the error it looks like numpy was not installed. I think miniconda
comes with no extra packages, so you'll need to install all dependencies.
Try running

pip install numpy

And then try again. It looks like you closed this thread, so you probably
already figured this out yourself.

Best wishes,
Alain

**Comment by learninguser** [comment]
Hi Alain,

Many thanks for your reply. First of all, thanks for developing a great tool for analysing GPR data under GNU Public License.

Yes, I figured it out myself. I was running it on an other environment which caused this error. But when I executed on the base environment the problem was solved.

It would be grateful, if you could provide me with some useful resources to know more about GPR data processing. Please also let me know if there any Polarimetric GPR datasets that could be shared with me are available with you. 

For your information, I have downloaded a copy of your PhD work from your website.

Thank you.
Kind regards
Pavan.

**Comment by AlainPlattner** [comment]
Hi Pavan,

I'm happy to hear. It's actually under MIT license, which is a bit more
liberal than the GNU license, for example, if a company wants to use it as
a base for commercial development, they are allowed to do that as long as
they recognize the original code. This would not be possible with a GNU
license. But that's the reason why you need to install the migration code
by running the installation script instead of just getting it automatically.

There seem to be a couple of good textbooks for GPR intro. I generally like
this one:
https://gpg.geosci.xyz/
Its free but it doesn't cover GPR processing in much detail (some day I may
contribute that part to it). A very good but pricy GPR book is Harry Jol's
"Ground Penetrating Radar Theory and Applications". You may find it in the
local University's library. There are of course many more and each has its
own philosophy. My personal opinion is that less processing is better and
if it's not visible in the raw data, then it shouldn't be trusted.

I've never worked with polarimetric data, so I don't have such a data set
and GPRPy, at the moment, is built for scalar data. If you come across a
good data set, can you please let me know, including specs on how the data
is encoded, such that I can write an import script for GPRPy?

Thanks and cheers,
Alain

**Comment by learninguser** [comment]
Hi Alain,
Thanks for sharing the useful resources on my request. Yes, I will share the polarimetric data with you once I find it.

Also if there any free datasets that are available with you, is it possible to share with me ? on which I could experiment my knowledge and may find something interesting with in these datasets.

Thanks for your help.
Kind regards
Pavan.
